---
- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache=true state=latest
  with_items:
  - bash
  - openssl
  - libssl-dev
  - libssl-doc
  tags: postgresql

- name: Install PostgreSQL
  apt: name={{ item }} update_cache=true state=installed
  with_items:
  - postgresql
  - postgresql-contrib
  - libpq-dev
  - python-psycopg2
  tags: postgresql

