---
- name: SONATA-NVF Service Platform CMUD 
  hosts: "{{ target }}"
  become: true

#  - include: "{{ operation }}/{{ service }}.yml"

- include: install/{{ service }}.yml
  when: operation == "install"

- include: manage/{{ action }}/{{ service }}.yml
  when: operation == "manage"

- include: upgrade/{{ service }}.yml
  when: operation == "upgrade"

- include: destroy/{{ service }}.yml
  when: operation == "destroy"

