---
# CENTOS 7

- name: postgresql database initialization
  command: "/usr/pgsql-9.6/bin/postgresql-setup initdb"

- name: starting postgresql database engine
  service: name=postgresql-{{ tarball }} state=started enabled=yes

- name: installing Odoo repo
  get_url:
    url: https://nightly.odoo.com/{{ tarball }}/nightly/rpm/odoo.repo
    dest: /etc/yum.repos.d/odoo.repo
    mode: 0644

- yum: name=* state=latest update_cache=yes

- name: installing ODOO
  yum: name=odoo state=present

- name: starting Odoo 
  service: name=odoo state=started enabled=yes

- name: install 'firewalld' to manage arbitrary ports/services
  yum: name=firewalld state=latest

