---
- name: stopping IFTA Docker containers at SP VM appliance
  hosts: "{{ target }}"
  become: true
  tasks:

  - name: Infrastructure Abstractor VIM Adaptor - stopping Docker containers
    docker_container:
      name: son-sp-infrabstract
      state: stopped

  - name: Infrastructure Abstractor WIM Adaptor - stopping Docker containers
    docker_container:
      name: wim-adaptor
      state: stopped

